#!/usr/bin/env python

#--- Option parsing ---#
"""
NY_misc: scripts from the Island of Lost Scripts

Usage:
  NY_misc [options] <command> [<args>...]
  NY_misc -h | --help
  NY_misc --version

Options:
  -p --perldoc  Get perldoc of command.
  -h --help     Show this screen.
  --version     Show version.

Commands:
  96well            -- well_IDs for a 96-well plate layout
  fasta_unwrap      -- unwrap a fasta file
  filter_seq        -- filter sequences
  geo_coord_convert -- convert geographic coordinates
  primerBarcodeList -- make a table of dual-indexed Illumina primers
  rInstallPackages  -- install r packages
  rnammer_filt      -- filter rnammer results

Description:
  This is the main command to call various scripts associated with this project.
"""

import os, sys
from docopt import docopt
from subprocess import call

scriptDir = os.path.dirname(__file__)
subcmdDir = os.path.join(scriptDir, 'bin')

if __name__ == '__main__':
    args = docopt(__doc__,
                  version='0.1',
                  options_first=True)


    # subcommand script
    exts = ['.pl', '.py', '.r']
    scriptFiles = [os.path.join(subcmdDir, args['<command>'] + ext) for ext in exts]
    scriptFiles = filter(os.path.isfile, scriptFiles)
    if len(scriptFiles) < 1:
        exit('"{}" is not a valid command. See "NY_misc -h".'.format(args['<command>']))

    
    # calling subcommand script
    cmd = [scriptFiles[0]] + args['<args>']
    if args['--perldoc']:
        cmd = ['perldoc'] + cmd    
    exit(call(cmd))
